name: Deploy to EC2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.315

      - name: Publish
        run: dotnet publish -c Release -o ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Trigger CodeDeploy
        env:
          CODEDEPLOY_APP: ${{ secrets.CODEDEPLOY_APP }}
          CODEDEPLOY_GROUP: ${{ secrets.CODEDEPLOY_GROUP }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Triggering AWS CodeDeploy"
          commit_hash=$(git rev-parse HEAD)
          aws deploy create-deployment \
            --application-name "$CODEDEPLOY_APP" \
            --deployment-group-name "$CODEDEPLOY_GROUP" \
            --github-location repository=${GITHUB_REPOSITORY},commitId=$commit_hash \
            --file-exists-behavior OVERWRITE \
            --region "$AWS_REGION"
